version: '3.0'

services:
    api:
        build: .
        container_name: edunext
        command: bash -c "python manage.py loaddata customerdataapi/initial_data.json && make run"
        volumes:
            - .:/code
        ports:
            - "8010:8010"