---
- hosts: all
  name: Deploying API to remote with docker
  gather_facts: no
  become: true
  tasks:
    - name: Install base packages for docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python-pip', 'virtualenv', 'python3-setuptools', 'python-setuptools', 'sqlite3']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install django Module
      pip:
        name: django

    - name: Install django framework
      pip:
        name: djangorestframework

    - name: Install pip docker-compose
      pip:
        name: docker-compose

    - name: Cloning project from github
      git:
        repo: 'https://github.com/jkauze/automated-api.git'
        dest: /root/edunext
        clone: yes
        update: yes

    - name: Tear down existing services docker
      docker_service:
        project_src: edunext
        state: absent

    - name: Create and start services docker
      docker_service:
        project_name: eduNEXT
        project_src: edunext
        state: present
      register: output

    - name: Migrate db and load initial data
      shell: cd edunext && docker-compose exec api python manage.py migrate && docker-compose exec api python manage.py loaddata customerdataapi/initial_data.json
